// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type SavedMovie struct {
	ID      int32
	MovieID int32
	UserID  uuid.UUID
}

type User struct {
	ID           uuid.UUID
	Name         string
	Email        string
	PasswordHash []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
